[package]
edition = "2021"
name = "rustdoc-json"
version = "0.7.4"
description = "Utilities for working with rustdoc JSON."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"
documentation = "https://docs.rs/rustdoc-json"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"

[dependencies]
cargo_metadata = "0.15.2"
cargo-manifest = "0.7.1"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
toml = "0.5.10"
log = { version = "0.4.17", optional = true }

[dev-dependencies]
assert_cmd = "2.0.7"
expect-test = "1.4.0"
tempfile = "3.3.0"

[dev-dependencies.predicates]
version = "2.1.5"
default-features = false

[dev-dependencies.public-api]
path = "../public-api"
version = "0.26.0"
